---
abstract: 'Simplified abstracted chained DBI subclass'
author:
  - 'Gryphon Shafer <gryphon@cpan.org>'
build_requires:
  Clone: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  constant: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.031, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Query
requires:
  Carp: '0'
  DBD::SQLite: '0'
  DBI: '0'
  SQL::Abstract::Complete: '0'
  SQL::Parser: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/gryphonshafer/DBIx-Query/issues
  homepage: https://github.com/gryphonshafer/DBIx-Query
  repository: https://github.com/gryphonshafer/DBIx-Query.git
version: '1.06'
